services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lecoursier
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lecoursier.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - lecoursier
      - traefik-public
    depends_on:
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.josemokeni.cloud`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"
    volumes:
      - pgadmin:/var/lib/pgadmin
  
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - lecoursier
  
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: soketi
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_ID: lecoursier
      SOKETI_DEFAULT_APP_KEY: lecoursier
      SOKETI_DEFAULT_APP_SECRET: lecoursier
      SOKETI_DEFAULT_APP_TOKEN: lecoursier
    ports:
      - "6001:6001"
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      # Main WebSocket route
      - "traefik.http.routers.soketi.rule=Host(`ws.josemokeni.cloud`)"
      - "traefik.http.services.soketi.loadbalancer.server.port=6001"
      - "traefik.http.routers.soketi.entrypoints=websecure"
      - "traefik.http.routers.soketi.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"
      # Alternative route for compatibility
      - "traefik.http.routers.soketi-alt.rule=Host(`josemokeni.cloud`) && PathPrefix(`/app/`)"
      - "traefik.http.routers.soketi-alt.entrypoints=websecure"
      - "traefik.http.routers.soketi-alt.tls.certresolver=leresolver"
      - "traefik.http.routers.soketi-alt.service=soketi"
    depends_on:
      - traefik

  # Redis commander
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_DATABASE=1
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`redis.josemokeni.cloud`)"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
      - "traefik.http.routers.redis-commander.entrypoints=websecure"
      - "traefik.http.routers.redis-commander.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"
    depends_on:
      - traefik
      - redis

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/acme.json:/acme.json
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik-public

  # Mail service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.josemokeni.cloud`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailhog.entrypoints=websecure"
      - "traefik.http.routers.mailhog.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"
    depends_on:
      - traefik
  
  documentation:
    image: josemokeni/lecoursier-documentation
    container_name: lecoursier-documentation
    restart: unless-stopped
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.documentation.rule=Host(`docs.lecoursier.josemokeni.cloud`)"
      - "traefik.http.services.documentation.loadbalancer.server.port=80"
      - "traefik.http.routers.documentation.entrypoints=websecure"
      - "traefik.http.routers.documentation.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"

volumes:
  pgdata:
  pgadmin:

networks:
  lecoursier:
    external: true
  traefik-public:
    external: true