services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
      - lecoursier
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lecoursier.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - default
      - lecoursier
      - traefik-public
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.josemokeni.cloud`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - lecoursier
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: soketi
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_ID: lecoursier
      SOKETI_DEFAULT_APP_KEY: lecoursier
      SOKETI_DEFAULT_APP_SECRET: lecoursier
      SOKETI_DEFAULT_APP_TOKEN: lecoursier
    ports:
      - 6001:6001
      - 9601:9601

    networks:
      - lecoursier

  # Redis commander
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_DATABASE=1
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`redis.josemokeni.cloud`)"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
      - "traefik.http.routers.redis-commander.entrypoints=websecure"
      - "traefik.http.routers.redis-commander.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"

  # traefik:
  #   image: traefik
  #   container_name: traefik
  #   restart: always
  #   command:
  #     - --providers.docker=true
  #     - --entrypoints.web.address=:80
  #     - --entrypoints.websecure.address=:443
  #     - --certificatesresolvers.leresolver.acme.httpchallenge=true
  #     - --certificatesresolvers.leresolver.acme.email=jmmokeni@gmail.com
  #     - --certificatesresolvers.leresolver.acme.storage=./docker/traefik/acme.json
  #     - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./docker/traefik/acme.json:/acme.json
  #     - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
  #   networks:
  #     - lecoursier
  #     - traefik-public
  #   labels:
  #     - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
  #     - "traefik.http.routers.http-catchall.entrypoints=web"
  #     - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
  #     - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # Mail service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    networks:
      - lecoursier
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.josemokeni.cloud`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailhog.entrypoints=websecure"
      - "traefik.http.routers.mailhog.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-public"

volumes:
  pgdata:
  pgadmin:

networks:
  lecoursier:
    external: true
  traefik-public:
    external: true
