[log]
  level = "DEBUG"

[accessLog]
  # Enables access logging for requests.
  filePath = "access.log"
  format = "json"

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"
